<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        Car::insert(
            [
    [
        'id' => 1,
        'year' => 2020,
        'price' => 20000,
        'mileage' => 15000,
        'vin' => 'VIN001',
        'address' => '123 Main St',
        'phone' => '1111111111',
        'description' => 'Toyota Corolla',
        'maker_id' => 1,
        'model_id' => 1,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 1,
        'city_id' => 1,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 2,
        'year' => 2021,
        'price' => 25000,
        'mileage' => 12000,
        'vin' => 'VIN002',
        'address' => '456 Oak St',
        'phone' => '2222222222',
        'description' => 'Toyota Camry',
        'maker_id' => 1,
        'model_id' => 2,
        'car_type_id' => 1,
        'fuel_type_id' => 2,
        'user_id' => 2,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 3,
        'year' => 2019,
        'price' => 18000,
        'mileage' => 30000,
        'vin' => 'VIN003',
        'address' => '789 Pine St',
        'phone' => '3333333333',
        'description' => 'Honda Civic',
        'maker_id' => 2,
        'model_id' => 3,
        'car_type_id' => 2,
        'fuel_type_id' => 1,
        'user_id' => 3,
        'city_id' => 3,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 4,
        'year' => 2022,
        'price' => 30000,
        'mileage' => 8000,
        'vin' => 'VIN004',
        'address' => '101 Maple St',
        'phone' => '4444444444',
        'description' => 'Honda Accord',
        'maker_id' => 2,
        'model_id' => 4,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 4,
        'city_id' => 4,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 5,
        'year' => 2018,
        'price' => 15000,
        'mileage' => 40000,
        'vin' => 'VIN005',
        'address' => '202 Cedar St',
        'phone' => '5555555555',
        'description' => 'Old Corolla',
        'maker_id' => 1,
        'model_id' => 1,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 1,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 6,
        'year' => 2023,
        'price' => 32000,
        'mileage' => 5000,
        'vin' => 'VIN006',
        'address' => '303 Birch St',
        'phone' => '6666666666',
        'description' => 'Nissan Altima',
        'maker_id' => 3,
        'model_id' => 5,
        'car_type_id' => 3,
        'fuel_type_id' => 2,
        'user_id' => 2,
        'city_id' => 3,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 7,
        'year' => 2020,
        'price' => 21000,
        'mileage' => 25000,
        'vin' => 'VIN007',
        'address' => '404 Elm St',
        'phone' => '7777777777',
        'description' => 'Mazda 3',
        'maker_id' => 4,
        'model_id' => 1,
        'car_type_id' => 2,
        'fuel_type_id' => 1,
        'user_id' => 5,
        'city_id' => 4,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 8,
        'year' => 2017,
        'price' => 14000,
        'mileage' => 50000,
        'vin' => 'VIN008',
        'address' => '505 Spruce St',
        'phone' => '8888888888',
        'description' => 'Hyundai Elantra',
        'maker_id' => 5,
        'model_id' => 2,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 1,
        'city_id' => 1,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 9,
        'year' => 2016,
        'price' => 13000,
        'mileage' => 60000,
        'vin' => 'VIN009',
        'address' => '606 Willow St',
        'phone' => '9999999999',
        'description' => 'Ford Focus',
        'maker_id' => 3,
        'model_id' => 3,
        'car_type_id' => 2,
        'fuel_type_id' => 1,
        'user_id' => 2,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 10,
        'year' => 2019,
        'price' => 17000,
        'mileage' => 35000,
        'vin' => 'VIN010',
        'address' => '707 Cherry St',
        'phone' => '1010101010',
        'description' => 'Chevrolet Cruze',
        'maker_id' => 4,
        'model_id' => 4,
        'car_type_id' => 3,
        'fuel_type_id' => 2,
        'user_id' => 3,
        'city_id' => 3,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    
    [
        'id' => 11,
        'year' => 2022,
        'price' => 28000,
        'mileage' => 10000,
        'vin' => 'VIN011',
        'address' => '808 Aspen St',
        'phone' => '1112223333',
        'description' => 'Kia Forte',
        'maker_id' => 6,
        'model_id' => 1,
        'car_type_id' => 1,
        'fuel_type_id' => 2,
        'user_id' => 4,
        'city_id' => 4,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 12,
        'year' => 2015,
        'price' => 11000,
        'mileage' => 80000,
        'vin' => 'VIN012',
        'address' => '909 Poplar St',
        'phone' => '4445556666',
        'description' => 'Nissan Sentra',
        'maker_id' => 3,
        'model_id' => 2,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 2,
        'city_id' => 1,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 13,
        'year' => 2023,
        'price' => 34000,
        'mileage' => 3000,
        'vin' => 'VIN013',
        'address' => '1010 Redwood St',
        'phone' => '7778889999',
        'description' => 'Subaru Impreza',
        'maker_id' => 7,
        'model_id' => 3,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 5,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 14,
        'year' => 2021,
        'price' => 31000,
        'mileage' => 7000,
        'vin' => 'VIN014',
        'address' => '1111 Walnut St',
        'phone' => '1231231234',
        'description' => 'Hyundai Tucson',
        'maker_id' => 5,
        'model_id' => 5,
        'car_type_id' => 3,
        'fuel_type_id' => 2,
        'user_id' => 3,
        'city_id' => 3,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 15,
        'year' => 2018,
        'price' => 16000,
        'mileage' => 42000,
        'vin' => 'VIN015',
        'address' => '1212 Beech St',
        'phone' => '9879879876',
        'description' => 'Volkswagen Jetta',
        'maker_id' => 8,
        'model_id' => 4,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 1,
        'city_id' => 4,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 16,
        'year' => 2017,
        'price' => 14500,
        'mileage' => 51000,
        'vin' => 'VIN016',
        'address' => '1313 Palm St',
        'phone' => '9990001111',
        'description' => 'Mazda CX-5',
        'maker_id' => 4,
        'model_id' => 2,
        'car_type_id' => 3,
        'fuel_type_id' => 1,
        'user_id' => 5,
        'city_id' => 1,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 17,
        'year' => 2020,
        'price' => 23000,
        'mileage' => 18000,
        'vin' => 'VIN017',
        'address' => '1414 Magnolia Ave',
        'phone' => '2223334444',
        'description' => 'Toyota Yaris',
        'maker_id' => 1,
        'model_id' => 3,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 2,
        'city_id' => 2,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 18,
        'year' => 2023,
        'price' => 45000,
        'mileage' => 2000,
        'vin' => 'VIN018',
        'address' => '1515 Cypress St',
        'phone' => '5556667777',
        'description' => 'Tesla Model 3',
        'maker_id' => 9,
        'model_id' => 1,
        'car_type_id' => 4,
        'fuel_type_id' => 3,
        'user_id' => 4,
        'city_id' => 3,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 19,
        'year' => 2019,
        'price' => 19000,
        'mileage' => 38000,
        'vin' => 'VIN019',
        'address' => '1616 Chestnut St',
        'phone' => '8889990000',
        'description' => 'Ford Fiesta',
        'maker_id' => 3,
        'model_id' => 4,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 3,
        'city_id' => 4,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 20,
        'year' => 2021,
        'price' => 26500,
        'mileage' => 12000,
        'vin' => 'VIN020',
        'address' => '1717 Fir St',
        'phone' => '1011011010',
        'description' => 'Chevrolet Malibu',
        'maker_id' => 4,
        'model_id' => 5,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 1,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],

    
    [
        'id' => 21,
        'year' => 2018,
        'price' => 17500,
        'mileage' => 39000,
        'vin' => 'VIN021',
        'address' => '1818 Hemlock St',
        'phone' => '2122122121',
        'description' => 'Honda Fit',
        'maker_id' => 2,
        'model_id' => 6,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 3,
        'city_id' => 5,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 22,
        'year' => 2019,
        'price' => 21000,
        'mileage' => 25000,
        'vin' => 'VIN022',
        'address' => '1919 Hickory St',
        'phone' => '3433433433',
        'description' => 'Nissan Rogue',
        'maker_id' => 3,
        'model_id' => 5,
        'car_type_id' => 3,
        'fuel_type_id' => 2,
        'user_id' => 2,
        'city_id' => 4,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 23,
        'year' => 2023,
        'price' => 32000,
        'mileage' => 9000,
        'vin' => 'VIN023',
        'address' => '2020 Spruce St',
        'phone' => '4544544544',
        'description' => 'Mazda 3 Hatchback',
        'maker_id' => 4,
        'model_id' => 4,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 5,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 24,
        'year' => 2017,
        'price' => 16000,
        'mileage' => 56000,
        'vin' => 'VIN024',
        'address' => '2121 Cottonwood Ave',
        'phone' => '5655655655',
        'description' => 'Ford Focus',
        'maker_id' => 3,
        'model_id' => 3,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 1,
        'city_id' => 3,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 25,
        'year' => 2020,
        'price' => 29500,
        'mileage' => 16000,
        'vin' => 'VIN025',
        'address' => '2222 Alder St',
        'phone' => '6766766766',
        'description' => 'Hyundai Elantra',
        'maker_id' => 5,
        'model_id' => 2,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 2,
        'city_id' => 1,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 26,
        'year' => 2024,
        'price' => 48000,
        'mileage' => 500,
        'vin' => 'VIN026',
        'address' => '2323 Elmwood Dr',
        'phone' => '7877877877',
        'description' => 'BMW 320i',
        'maker_id' => 10,
        'model_id' => 1,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 4,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 27,
        'year' => 2022,
        'price' => 36500,
        'mileage' => 8000,
        'vin' => 'VIN027',
        'address' => '2424 River Rd',
        'phone' => '8988988988',
        'description' => 'Audi A3',
        'maker_id' => 11,
        'model_id' => 2,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 5,
        'city_id' => 4,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 28,
        'year' => 2016,
        'price' => 12500,
        'mileage' => 64000,
        'vin' => 'VIN028',
        'address' => '2525 Oakwood Ave',
        'phone' => '9099099099',
        'description' => 'Chevrolet Spark',
        'maker_id' => 4,
        'model_id' => 3,
        'car_type_id' => 1,
        'fuel_type_id' => 1,
        'user_id' => 1,
        'city_id' => 5,
        'published_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 29,
        'year' => 2021,
        'price' => 27500,
        'mileage' => 10000,
        'vin' => 'VIN029',
        'address' => '2626 Highland Ave',
        'phone' => '1211211211',
        'description' => 'Toyota Corolla Cross',
        'maker_id' => 1,
        'model_id' => 4,
        'car_type_id' => 3,
        'fuel_type_id' => 2,
        'user_id' => 2,
        'city_id' => 2,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 30,
        'year' => 2024,
        'price' => 51000,
        'mileage' => 1000,
        'vin' => 'VIN030',
        'address' => '2727 Bay St',
        'phone' => '2322322323',
        'description' => 'Mercedes-Benz A200',
        'maker_id' => 12,
        'model_id' => 5,
        'car_type_id' => 2,
        'fuel_type_id' => 2,
        'user_id' => 3,
        'city_id' => 1,
        'published_at' => now(),
        'created_at' => now(),
        'updated_at' => now(),
    ],


]

        );


        // make a factory for this this is the most noob way of doing it go to factory and i wrote their how to do it 
    }
}
